# Serve
baseurl: /about
url:     http://thirtyjin.com

source: src
destination: _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# ensures SCSS files are compiled
include: [_*.scss]


# plugins
plugins:
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-toc


# site
title: THIRTYJIN の 设计进化论
description: THIRTYJIN の 设计进化论。

lang: zh

# Custom variables
site_url:       http://thirtyjin.com
blog_url:       http://thirtyjin.com/blog/

author:
  name:         Thirty Jin

dux:
  duxicons:     http://thirtyjin.com/dux_icons
  duxicons_git: https://github.com/DuxDesign/dux_icons
  duxlibs:      http://thirtyjin.com/dux_libs
  duxlibs_git:  https://github.com/DuxDesign/dux_libs
  duxcharts:    http://thirtyjin.com/dux_charts
  duxcharts_git:  https://github.com/DuxDesign/dux_charts

contact:
  email:        mailto:thirty.jin@gmail.com
  twitter:      https://twitter.com/thirtyjin
  github:       https://github.com/thirtyjin
  weibo:        https://weibo.com/thirtyjin
  weixin:       thirtyjin
  facebook:     http://www.facebook.com/thirtyjin
  dribbble:     http://dribbble.com/thirtyjin
  linkedin:     http://www.linkedin.com/in/thirtyjin/

github:
  url:          https://github.com/thirtyjin/thirtyjin.github.io
  project:      thirtyjin
  org:          thirtyjin

license:
  font:
    version:      SIL OFL 1.1
    url:          http://scripts.sil.org/OFL
  code:
    version:      MIT License
    url:          http://opensource.org/licenses/mit-license.html
  documentation:
    version:      CC BY 3.0
    url:          http://creativecommons.org/licenses/by/3.0/
